# Generated by Django 3.2.6 on 2021-08-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.PositiveSmallIntegerField(choices=[(0, 'ngn'), (1, 'usd'), (2, 'oth')], default=0),
        ),
    ]
