# Generated by Django 3.2.6 on 2021-08-23 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('name_on_card', models.CharField(max_length=100)),
                ('card_pan', models.CharField(max_length=16, unique=True)),
                ('card_hash', models.CharField(max_length=200, unique=True)),
                ('cvv', models.CharField(max_length=3)),
                ('expiration_date', models.DateTimeField()),
                ('card_type', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
